apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'jenkins'
        metrics_path: '/prometheus'
        static_configs:
          - targets: ['3.109.209.35:32000']
      - job_name: 'kube-state'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['3.110.32.38:30401']
      - job_name: 'prometheus'
        static_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
          target_label: instance
          action: replace
          regex: (.+)
          replacement: $1:9100  # Node Exporter port